Opgops 1691
ministryofjustice/opg-salt-formula pull request #40
Opened 2017-03-24 14:38 UTC by brettminnie

Add container for dashboards to monitoring server config

2017-03-27 16:39 UTC, tim-mcarthur-moj requested changes

2017-03-27 16:39 UTC, tim-mcarthur-moj commented on elastic-beats/templates/metricbeat.yml.j2
> +    #- module: docker
is this not going to replace the dockbeats.  so should be enabled in the template

2017-03-27 16:47 UTC, brettminnie commented
:+1:

Just need to test it before I do that

On Mon, Mar 27, 2017 at 5:39 PM, tim-mcarthur-moj <notifications@github.com>
wrote:

> *@tim-mcarthur-moj* requested changes on this pull request.
> ------------------------------
>
> In elastic-beats/templates/metricbeat.yml.j2
> <https://github.com/ministryofjustice/opg-salt-formula/pull/40#discussion_r108218097>
> :
>
> > +    - module: system
> +      metricsets:
> +        - cpu
> +        - load
> +        - filesystem
> +        - fsstat
> +        - memory
> +        - network
> +        - process
> +        - socket
> +      enabled: true
> +      period: 10s
> +      processes: ['.*']
> +
> +    #------------------------------- Docker Module -------------------------------
> +    #- module: docker
>
> is this not going to replace the dockbeats. so should be enabled in the
> template
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ministryofjustice/opg-salt-formula/pull/40#pullrequestreview-29235931>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AF1y2L0zjcCgcX1Nl7iJjdUUMVxYg_Aeks5rp-ZEgaJpZM4MoVoI>
> .
>

2017-03-28 08:34 UTC, tim-mcarthur-moj requested changes

2017-03-28 08:34 UTC, tim-mcarthur-moj commented on elastic-beats/templates/topbeat.yml.j2
> -  procs: ["php.*", "nginx.*","java.*","docker.*","mongo.*","salt.*","python.*","collectdmon.*"]
this config needs to be transferred to metricbeats.  this reduces the disk space requirement and is targeted for our applications. this should probably be set based on the elastic-beats:metricbeat pillar

2017-03-28 08:38 UTC, brettminnie commented
:+1:

It's of course named processes in metricbeats

On Tue, Mar 28, 2017 at 9:34 AM, tim-mcarthur-moj <notifications@github.com>
wrote:

> *@tim-mcarthur-moj* requested changes on this pull request.
> ------------------------------
>
> In elastic-beats/templates/topbeat.yml.j2
> <https://github.com/ministryofjustice/opg-salt-formula/pull/40#discussion_r108362763>
> :
>
> > @@ -1,165 +0,0 @@
> -################### Topbeat Configuration Example #########################
> -
> -############################# Input ############################################
> -input:
> -  period: 10
> -  procs: ["php.*", "nginx.*","java.*","docker.*","mongo.*","salt.*","python.*","collectdmon.*"]
>
> this config needs to be transferred to metricbeats. this reduces the disk
> space requirement and is targeted for our applications. this should
> probably be set based on the elastic-beats:metricbeat pillar
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ministryofjustice/opg-salt-formula/pull/40#pullrequestreview-29387269>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AF1y2MZxdJNl0iwUjGR4dG2ln2w-yWD4ks5rqMYegaJpZM4MoVoI>
> .
>

2017-03-28 09:45 UTC, tim-mcarthur-moj requested changes

2017-03-28 09:45 UTC, tim-mcarthur-moj commented on monitoring/templates/compose-monitoring-server.yml
>  {%- else %}
how do the templates get imported when **remote_elastic** is 'no'

2017-03-28 10:48 UTC, tim-mcarthur-moj approved these changes

2017-03-28 10:49 UTC, merged